spring.application.name=studentassistant
spring.datasource.url=jdbc:postgresql://ep-empty-morning-anthh9qp-pooler.c-6.us-east-1.aws.neon.tech/Student_Assistant?user=neondb_owner&password=npg_d5RIsAUyJKh0&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_d5RIsAUyJKh0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update